[package]
name = "resist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.30.0", features = ["fs"] }
rand = "0.8.5"
